name: Main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Restore Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Create Coverage Directory
        run: mkdir coverage

      - name: Run Unit Tests
        run: npm run test -- --coverage

      - name: Generate Test Coverage
        run: npm run test:generate-output:build

      - name: Build Projects
        run: npm run build
